{% set name = "hist" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hist-{{ version }}.tar.gz
  sha256: 0de95877b64e2968dbec5267786e6b5d327045152c46d4e387cc9b5181a9d4b3

build:
  number: 0
  noarch: python
  entry_points:
    - hist=hist.classichist:main
  script: {{ PYTHON }} -m pip install ".[plot]" -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - boost-histogram ~=0.13.0
    - histoprint >=1.6
    - numpy >=1.13.3
    - python >=3.6
    # Actually only required for [py<38] but require for all Python versions so this can be noarch: python
    - typing-extensions
    # The plot requirements - could be changed eventually to be hist-core and hist
    - matplotlib-base >=3.0
    - mplhep >=0.2.16
    - scipy >=1.1
    - uncertainties >=3

test:
  imports:
    - hist
    - hist.axis
  commands:
    - pip check
    - hist --help
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/hist
  summary: Hist classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chrisburr
    - henryiii
    - LovelyBuggies
