{% set name = "hist" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hist-{{ version }}.tar.gz
  sha256: a9692668ff0f5e9d381e99e7df501962e6b28dd77b5d3d309ef1b3de3cb634cd

build:
  number: 0
  noarch: python
  entry_points:
    - hist=hist.classichist:main
  script: {{ PYTHON }} -m pip install ".[plot]" -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - boost-histogram ~=1.1.0
    - histoprint >=1.6
    - numpy >=1.13.3
    - python >=3.6
    # Actually only required for [py<38] but require for all Python versions so this can be noarch: python
    - typing-extensions
    # The plot requirements - could be changed eventually to be hist-core and hist
    - matplotlib-base >=3.0
    - mplhep >=0.2.16
    - scipy >=1.1
    - uncertainties >=3

test:
  imports:
    - hist
    - hist.axis
  commands:
    - pip check
    - hist --help
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/hist
  summary: Hist classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
    - LovelyBuggies
