{% set name = "hist" %}
{% set version = "2.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hist-{{ version }}.tar.gz
  sha256: bf1ab7f79d848e47552d8f8efd00d574f0bdd3a200e2b6319e3e4c17e5cc78a4

build:
  number: 0
  noarch: python
  entry_points:
    - hist=hist.classichist:main
  script: {{ PYTHON }} -m pip install ".[plot]" -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools_scm
  run:
    - boost-histogram ~=1.3.1
    - histoprint >=2.2
    - numpy >=1.14.5
    - python >=3.7
    # Actually only required for [py<38] but require for all Python versions so this can be noarch: python
    - typing-extensions
    # The plot requirements - could be changed eventually to be hist-core and hist
    - matplotlib-base >=3.0
    - mplhep >=0.2.16
    - scipy >=1.4
    - iminuit >=2.0

test:
  imports:
    - hist
    - hist.axis
  commands:
    - pip check
    - hist --help
  requires:
    - pip

about:
  home: https://github.com/scikit-hep/hist
  summary: Hist classes and utilities
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/scikit-hep
    - LovelyBuggies
